version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DB_NAME: your_database_name
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
